# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 428a87a2d0924a77f7cee4375c51f34b6a273f86071d4de4167755586a02853182097d0258df795c1f4f535d5108409567ea0ec9d28b702977a1a1d7238e74bb

test:
  secret_key_base: 2566bb2c846c6052f3d2936577fb50ef170bd82da9be8e0c670e1543ea8333b31e9f6899c252ce4a7e79dac015bddf206045092e136609e7fdef06c6985c57e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
